apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "upday.fullname" . }}
spec:
  maxUnavailable: 2
  selector:
    matchLabels: 
      {{- include "upday.selectorLabels" . | nindent 6 }}
